/**
 * Task card identifiers, shared by the server and the renderer.
 *
 * A card's ULID is generated by whichever side creates the card first. The
 * renderer mints the id at composer commit so its optimistic row and the
 * server's authoritative row are the same card from the first frame — no
 * temp-id swap, no re-keyed DOM, and a safe idempotent retry after a dropped
 * response. The time-prefixed Crockford encoding keeps ids lexically ordered
 * by creation time, matching the server's historical `createTaskUlid`.
 */

const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
const TIME_LENGTH = 10
const RANDOM_LENGTH = 16
const TASK_ULID_PATTERN = /^[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26}$/

export const createTaskUlid = (time = Date.now()): string => {
  let timestamp = time
  let encodedTime = ''
  for (let index = 0; index < TIME_LENGTH; index += 1) {
    encodedTime = CROCKFORD[timestamp % 32] + encodedTime
    timestamp = Math.floor(timestamp / 32)
  }
  // Web Crypto is available in both the Bun server and the renderer; the
  // historical server implementation used node:crypto, which the renderer
  // cannot import.
  const entropy = globalThis.crypto.getRandomValues(
    new Uint8Array(RANDOM_LENGTH)
  )
  let encodedRandom = ''
  for (let index = 0; index < RANDOM_LENGTH; index += 1) {
    encodedRandom += CROCKFORD[(entropy[index] ?? 0) % 32]
  }
  return encodedTime + encodedRandom
}

/** True only for the 26-character Crockford ULID this module generates. */
export const isTaskUlid = (value: string): boolean =>
  TASK_ULID_PATTERN.test(value)
