/**
 * Snapshot cache helpers for Daytona sandbox dependency caching.
 *
 * Pure functions for computing cache keys and generating snapshot names.
 * These helpers are used by `DaytonaSandboxProvider.createSandbox` to
 * cache project dependencies as Daytona snapshots, avoiding repeated
 * `npm install` / `bun install` on every workspace creation.
 *
 * Lockfile detection is provided by `detectLockfile` from `deps-image-service.ts`.
 * Project slug sanitization uses `sanitizeProjectSlug` from the same module.
 *
 * The caching strategy mirrors `DepsImageService` (Docker flow) but
 * uses Daytona's snapshot infrastructure instead of Docker images.
 *
 * @see packages/server/src/services/daytona-sandbox-provider.ts
 * @see docs/daytona-sandbox-provider/issues.md (Issue 21)
 */

import { createHash } from 'node:crypto'

import { sanitizeProjectSlug } from '../services/deps-image-service.js'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Prefix for snapshot names generated by laborer.
 * Used to namespace laborer's cached dependency snapshots and avoid
 * collision with user-created snapshots.
 */
const SNAPSHOT_NAME_PREFIX = 'laborer-deps'

/**
 * Maximum length for Daytona snapshot names.
 * Daytona's API has a name length constraint — we truncate to stay within it.
 */
const MAX_SNAPSHOT_NAME_LENGTH = 63

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/**
 * Build a cache hash from a lockfile hash and an optional base image name.
 *
 * When a base image is specified, the cache key includes the image name
 * so that different base images produce different snapshots even with
 * the same lockfile. This matches the `DepsImageService` pattern.
 *
 * @param lockfileHash - SHA-256 hash of the lockfile content (first 12 chars)
 * @param baseImage - Optional base image name (e.g., "node:22")
 * @returns SHA-256 hash (first 12 chars) of the combined key
 */
const buildCacheHash = (lockfileHash: string, baseImage?: string): string => {
  const input =
    baseImage != null ? `${lockfileHash}:${baseImage}` : lockfileHash
  return createHash('sha256').update(input).digest('hex').slice(0, 12)
}

/**
 * Build a Daytona snapshot name from a project name and cache hash.
 *
 * Format: `laborer-deps-{projectSlug}-{cacheHash}`
 *
 * The name is sanitized and truncated to fit within Daytona's snapshot
 * name length limit.
 *
 * @param projectName - Human-readable project name
 * @param cacheHash - The combined lockfile + image cache hash (12 chars)
 * @returns A valid Daytona snapshot name
 */
const buildSnapshotName = (projectName: string, cacheHash: string): string => {
  const slug = sanitizeProjectSlug(projectName)
  const name = `${SNAPSHOT_NAME_PREFIX}-${slug}-${cacheHash}`
  return name.slice(0, MAX_SNAPSHOT_NAME_LENGTH)
}

export {
  buildCacheHash,
  buildSnapshotName,
  MAX_SNAPSHOT_NAME_LENGTH,
  SNAPSHOT_NAME_PREFIX,
}
